### ISSUE TITLE
options.base does not work

### ISSUE THREAD

**Issue by dabendan2** [LionC/persistent-cache#4]
From your document, I passed options.base into cache(), but it does not work.
Then I looked into the code, and use options.dir instead, but still don't work.
The operator precedence of || is higher then ?:
```js
var base = path.normalize(
        (options.dir || require.main ? 
		path.dirname(require.main.filename) : 
		undefined || process.cwd()
	)  + '/cache'
    );
```

**Comment by LionC** [comment]
You are right, thanks. Ill try to fix it tomorrow (and add a test for that)

**Comment by LionC** [comment]
Should be fixed
